### PR TITLE
Automatically wrap code in at-enter/run macros

### LINKED ISSUE #222: Automatically wrap expression passed to @enter in a function?
Currently, `@enter` fails with complex expressions like broadcasting and do notation.  I usually just wrap them in a function and call `@enter`.  Is it reasonable to do this automatically?

### PR DESCRIPTION
**Pull request by tkf**
close #222 

It works, but strangely the closing bracket is missing in this example:

```julia
julia> @enter exp.(1 .+ 2)
In ##thunk#381() at REPL[24]:1
>1  @enter exp.(1 .+ 2

About to run: (Base.Broadcast.broadcasted)(+, 1, 2)
1|debug>
```

### CODE REVIEW

File: src/Debugger.jl [hunk 1]
```diff
@@ -95,24 +95,35 @@ function _make_frame(mod, arg)
     end
 end
 
-_check_is_call(arg) = isexpr(arg, :call) || throw(ArgumentError("@enter and @run should be applied to a function call"))
+function _preprocess_enter(__source__, ex)
+    if isexpr(ex, :call)
```
Comment (tkf) [inline src/Debugger.jl]: This still catches the cases like `@enter 1 .+ 2`.  What's the best way to detect it?  `startswith(string(ex.args[1]), ".")`?

**Comment by tkf** [comment]
Can this be merged? I've been using this branch for a while but I don't remember having a major issue because of this.

**Comment by KristofferC** [comment]
Let's try it then.
