### PR TITLE
fix f and fr

### LINKED ISSUE #92: `fr n` goes to frame `n`
The description says:
```
  - fr [v::Int]: show all variables in the current frame, v defaults to 1
  - f [n::Int]: go to the n-th frame
```
It sounds like `fr 2` should just show variables and not change the frame, which it currently does. Personally I think we can remove `f` completely (instead of just fixing the docs or behavior of `fr n`), and have:
```
  - fr: show all variables in the current frame
  - fr n::Int: go to the n-th frame
```

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes #92 and fixes https://github.com/JuliaDebug/Debugger.jl/issues/91

This puts a bit of source code from Base into the tests but that part hasnt been touched for years so should be ok.

### CODE REVIEW

File: src/commands.jl [hunk 1]
```diff
@@ -76,23 +76,36 @@ end
...
+    subcmds = split(cmd, ' ')
+    if length(subcmds) == 1
+        new_level = 1
     else
-        new_level = parse(Int, subcmds[1])
-        if new_level > stacklength(state.frame) || new_level < 1
-            printstyled(stderr, "Not a valid frame index\n"; color=:red)
+        new_level = tryparse(Int, subcmds[2])
+        if new_level == nothing
+            printstyled(stderr, "Failed to parse $(subcmds[2]) as an integer\n"; color=:red)
```
Comment (fredrikekre) [inline src/commands.jl]:
```suggestion
            printstyled(stderr, "Failed to parse $(repr(subcmds[2])) as an integer\n"; color=:red)
```
