### PR TITLE
fix evals when the value is a symbols

### LINKED ISSUE #127: Missing quote on Symbols
MWE:
```
julia> @enter f()
In f() at REPL[10]:2
>2      x = Symbol("abc")
 3      return x
 4  end

About to run: (Symbol)("abc")
1|debug> n
In f() at REPL[10]:2
 2      x = Symbol("abc")
>3      return x
 4  end

About to run: return :abc
1|debug> w add x
1|debug> w
1] x: UndefVarError(:abc)

1|julia> 1+1
ERROR: UndefVarError: abc not defined
Stacktrace:
 [1] top-level scope at none:0
 [2] eval at ./boot.jl:319 [inlined]
```

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes #127

### CODE REVIEW

File: test/evaling.jl [hunk 1]
```diff
@@ -33,3 +33,9 @@ evalkw(x; bar=true) = x
 frame = @make_frame evalkw(2)
 res = eval_code(frame, "x")
 @test res == 2
+
+# Evaling with symbols
+evalsym() = (x = :foo)
+frame = @make_frame evalkw(2)
```
Comment (fredrikekre) [inline test/evaling.jl]:
```suggestion
frame = @make_frame evalsym(2)
```

**Comment by KristofferC** [comment]
Added a test for watch expression.
