### PR TITLE
Fix file we look for source code in

### LINKED ISSUE #71: BoundsError with a logging statement in the function
```
julia> function f()
           x = 1 + 1
           @info "hello"
       end
f (generic function with 1 method)

julia> @enter f()
In f() at REPL[2]:2
2     x = 1 + 1
3     @info "hello"
4 end

About to run: (+)(1, 1)
1|debug> s
In +(x, y) at int.jl:53
53  (+)(x::T, y::T) where {T<:BitInteger} = add_int(x, y)
54  (*)(x::T, y::T) where {T<:BitInteger} = mul_int(x, y)
55  

About to run: (add_int)(1, 1)
1|debug> s
In +(x, y) at int.jl:53
53  (+)(x::T, y::T) where {T<:BitInteger} = add_int(x, y)
54  (*)(x::T, y::T) where {T<:BitInteger} = mul_int(x, y)
55  

About to run: return 2
1|debug> s
ERROR: BoundsError: attempt to access 4-element Array{UInt64,1} at index [306]
Stacktrace:
 [1] getindex at ./array.jl:731 [inlined]
 [2] #print_sourcecode#4(::Debugger.LineNumbers.SourceFile, ::Function, ::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::String, ::Int64, ::Int64) at /home/fredrik/.julia/packages/Debugger/aNxIq/src/locationinfo.jl:92
 [3] print_sourcecode at /home/fredrik/.julia/packages/Debugger/aNxIq/src/locationinfo.jl:92 [inlined]
 [4] print_status(::Base.TTY, ::JuliaInterpreter.Frame) at /home/fredrik/.julia/packages/Debugger/aNxIq/src/printing.jl:88
 [5] (::getfield(Debugger, Symbol("##7#11")){REPL.Terminals.TTYTerminal,Debugger.DebuggerState,REPL.LineEdit.Prompt})(::REPL.LineEdit.MIState, ::Base.GenericIOBuffer{Array{UInt8,1}}, ::Bool) at /home/fredrik/.julia/packages/Debugger/aNxIq/src/repl.jl:54
 [6] #invokelatest#1 at ./essentials.jl:697 [inlined]
 [7] invokelatest at ./essentials.jl:696 [inlined]
 [8] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /home/fredrik/julia10/usr/share/julia/stdlib/v1.0/REPL/src/LineEdit.jl:2273
 [9] run_interface at /home/fredrik/julia10/usr/share/julia/stdlib/v1.0/REPL/src/LineEdit.jl:2267 [inlined]
 [10] #RunDebugger#5(::Bool, ::Function, ::JuliaInterpreter.Frame, ::REPL.LineEditREPL, ::REPL.Terminals.TTYTerminal) at /home/fredrik/.julia/packages/Debugger/aNxIq/src/repl.jl:82
 [11] RunDebugger(::JuliaInterpreter.Frame, ::REPL.LineEditREPL, ::REPL.Terminals.TTYTerminal) at /home/fredrik/.julia/packages/Debugger/aNxIq/src/repl.jl:4 (repeats 2 times)
 [12] top-level scope at /home/fredrik/.julia/packages/Debugger/aNxIq/src/Debugger.jl:82
```

### LINKED ISSUE #77: Error stepping through macro generated code
I was trying to debug the following
```
using Core.Compiler: IRCode, argextype, Const
function generate_rule(rule, stmt, done_sym)
    if isexpr(rule, :call)
        call_match = quote
            isexpr($stmt, :call) || @goto $(done_sym)
            ft = argextype($stmt.args[1], ir, ir.sptypes)
            isa(ft, Const) || @goto $(done_sym)
            ft.val === $(rule.args[1]) || @goto $(done_sym)
        end
        argsyms = [gensym() for _ = 1:length(rule.args)-1]
        quote
            $call_match
            $(map(i->:($(argsyms[i]) = $stmt.args[1+$i]), 1:length(argsyms))...)
            $(map(i->generate_rule(rule.args[1+i], argsyms[i], done_sym), 1:length(argsyms))...)
        end
    elseif isexpr(rule, :(::))
        argsym = gensym()
        return quote
            sT = argextype($stmt.args[2], ir, ir.sptypes)
            sT ⊑ $(rule.args[2]) || @goto $(done_sym)
            $(argsym) = $stmt.args[1]
            $(generate_rule(rule.args[1], argsym, done_sym))
        end
    elseif isa(rule, Symbol)
        name = String(rule)
        name == "_" && return nothing
        :($rule = $stmt)
    end
end

function generate_replacement(replacement)
    :(ir.stmts[idx] = Expr(:call, size, bc))
end

macro rule(expr)
    @capture(expr, pattern_ => replacement_)
    label = gensym()
    esc(quote
        $(generate_rule(pattern, :stmt, label))
        $(generate_replacement(replacement))
        return
        @label($label)
    end)
end

function array_optimize!(ir, idx)
    stmt = ir.stmts[idx]
    @rule size(materialize(bc::Broadcasted)) => size(bc)
end
```
Error is:
```
ERROR: BoundsError: attempt to access 4-element Array{UInt64,1} at index [5]
Stacktrace:
 [1] getindex at ./array.jl:728 [inlined]
 [2] #print_sourcecode#28(::Debugger.LineNumbers.SourceFile, ::typeof(Debugger.print_sourcecode), ::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::String, ::Int64, ::Int64) at /home/keno/.julia/packages/Debugger/rxJeq/src/printing.jl:149
 [3] print_sourcecode at /home/keno/.julia/packages/Debugger/rxJeq/src/printing.jl:149 [inlined]
 [4] print_status(::Base.TTY, ::Frame) at /home/keno/.julia/packages/Debugger/rxJeq/src/printing.jl:88
 [5] (::getfield(Debugger, Symbol("##5#9")){REPL.Terminals.TTYTerminal,Debugger.DebuggerState,REPL.LineEdit.Prompt})(::REPL.LineEdit.MIState, ::Base.GenericIOBuffer{Array{UInt8,1}}, ::Bool) at /home/keno/.julia/packages/Debugger/rxJeq/src/repl.jl:54
 [6] #invokelatest#1 at ./essentials.jl:790 [inlined]
 [7] invokelatest at ./essentials.jl:789 [inlined]
 [8] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /home/keno/julia/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:2306
 [9] run_interface at /home/keno/julia/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:2300 [inlined]
 [10] #RunDebugger#3(::Bool, ::typeof(Debugger.RunDebugger), ::Frame, ::REPL.LineEditREPL, ::REPL.Terminals.TTYTerminal) at /home/keno/.julia/packages/Debugger/rxJeq/src/repl.jl:82
 [11] RunDebugger(::Frame, ::REPL.LineEditREPL, ::REPL.Terminals.TTYTerminal) at /home/keno/.julia/packages/Debugger/rxJeq/src/repl.jl:4 (repeats 2 times)
 [12] top-level scope at /home/keno/.julia/packages/Debugger/rxJeq/src/Debugger.jl:82
```
Reproduce with e.g.:
```
ir = Core.Compiler.inflate_ir((@code_typed gcd(10, 20)).first)
@enter array_optimize!(ir, 5)
```

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes #71 
Fixes #77

### CODE REVIEW

**Comment by KristofferC** [comment]
Need to look at how `defline` is used. If we are in another file than the current method `defline` should not have any influence how we print the status.

**Comment by timholy** [comment]
Should also be fixed by https://github.com/timholy/CodeTracking.jl/pull/17

**Comment by timholy** [comment]
Actual, I'm going to nvm my nvm. Just calling it on the frame should fix it once CodeTracking updates.

**Comment by timholy** [comment]
Cautionary: https://github.com/timholy/CodeTracking.jl/issues/18. I don't think there's anything we can do about that without modifying Julia itself.

File: src/locationinfo.jl [hunk 1]
```diff
@@ -35,9 +35,10 @@ end
 function locinfo(frame::Frame)
     if frame.framecode.scope isa Method
         meth = frame.framecode.scope
-        file, def_line = JuliaInterpreter.whereis(meth)
-        _, current_line = JuliaInterpreter.whereis(frame)
-        return loc_for_fname(file, current_line, def_line)
+        def_file, def_line = JuliaInterpreter.whereis(meth)
+        current_file, current_line = JuliaInterpreter.whereis(frame)
+        def_line > current_line && (def_line = 1) # This can happen in e.g. macro expansions
```
Comment (timholy) [inline src/locationinfo.jl]: Is this just to prevent `BoundsError`? Otherwise it doesn't seem particularly reliable.

Comment (KristofferC) [reply src/locationinfo.jl]: Bascially `def_line` provides a "roof" where we do not print source code above it. Because if we are in `sin` we do not want to print code above the `sin` definition.

However, if we are in another file such a roof doesnt make sense. Setting this to `1` just mean that we will print the maximum number of source lines.

Comment (KristofferC) [reply src/locationinfo.jl]: But yeah, perhaps this is the wrong place to do this since it isn't really location info anymore, just data for the source code printer to do its job as good as it can.

Comment (timholy) [reply src/locationinfo.jl]: Thanks for the explanation. I'm fine with whatever you choose. Perhaps add a code comment explaining these issues?

Comment (KristofferC) [reply src/locationinfo.jl]: Actually this should be `= 0` since the commend for `def_line` says 

```
    # The line at which the current context starts, 0 if unknown
```

Comment (KristofferC) [reply src/locationinfo.jl]: Pushed an update
